ActivityDirector = {}
function ActivityDirector.LogActivityPush() end
function ActivityDirector.LogDirectActivityRequest() end 
function ActivityDirector.LogLongTimeWithoutPush() end 
function ActivityDirector.RequestMission() end
function ActivityDirector.RequestNewActivity() end 
Chat = {}
function Chat.GetAnon() end
function Chat.GetChannelList() end
function Chat.GetInstanceID() end
function Chat.GetLFG() end
function Chat.GetLocalUserInfo() end
function Chat.GetPlayersInZone() end
function Chat.GetPlayersLFG() end
function Chat.GetUserInfo() end
function Chat.SendChannelText() end
function Chat.SendWhisperText() end
function Chat.SetLFG() end
function Chat.ToggleAnon() end
function Chat.ToggleLFG() end
Component = {}
function Component.ActivateUserKeybinds() end
function Component.AreUserKeybindsActive() end
function Component.BeginDragDrop() end
function Component.BindUserKey() end
function Component.CreateAnchor() end
function Component.CreateFrame() end
function Component.CreateRenderTarget() end
function Component.CreateSceneObject() end
function Component.DebugSaveTexture() end
function Component.EndDragDrop() end
function Component.FosterWidget() end
function Component.FosterWidget() end
function Component.GenerateEvent() end
function Component.GetFrame() end
function Component.GetInfo() end
function Component.GetSetting() end
function Component.GetSettingKeys() end
function Component.GetTextureInfo() end
function Component.GetTitleSafe() end
function Component.GetUserBoundKey() end
function Component.GetWidget() end
function Component.IsWidget() end
function Component.LookupColor() end --key = red,green,blue,alpha,rgb,argb
function Component.LookupText() end
function Component.PostMessage() end
function Component.RegisterKeyAction() end
function Component.RemoveAnchor() end
function Component.RemoveFrame() end
function Component.RemoveLocalizationTracking() end
function Component.RemoveRenderTarget() end
function Component.RemoveSceneObject() end
function Component.RemoveWidget() end
function Component.SaveSetting() end
function Component.SetDragAccept() end
function Component.SetInputMode() end
function Component.SetRenderTargetRegion() end
function Component.UnregisterKeyAction() end
Databse = {}
function Databse.GetHeadAccessoryInfo() end
function Databse.GetHeadInfo() end
Friends = {}
function Friends.AddFriend() end
function Friends.GetList() end
function Friends.GetRequest() end
function Friends.RemoveFriend() end
function Friends.UpdateMyPresence() end
Game = {}
function Game.AcceptPvPMatch() end
function Game.AcceptPvPMatch() end
function Game.acceptResourceScan() end
function Game.AddRecipeToCart() end
function Game.CallMenuAction() end
function Game.CanTrackRecipe() end
function Game.ChunkCoordToWorld() end
function Game.ClearTrail() end
function Game.ClearWayPoint() end
function Game.ConfirmDuel() end
function Game.FindServiceProvider() end
function Game.GetArmyInfo() end
function Game.GetAvailableTargets() end
function Game.GetCameraPos() end
function Game.GetCertificateInfo() end
function Game.GetCharacterTypeInfo() end
function Game.GetEncounterUiFields() end
function Game.GetFoundMatch() end
function Game.GetFrameConstaintsMultipliers() end
function Game.GetGameVariable() end
function Game.GetItemAttributeModifiers() end
function Game.GetItemInfoByType() end
function Game.GetItemTypesOfResourceType() end
function Game.GetKnownResourceLocations() end
function Game.GetLoadoutInfoByType() end
function Game.GetMapMarkerInfo() end
function Game.GetMapMarkerList() end
function Game.GetPreviewItemInfo() end
function Game.GetPvPMatchId() end
function Game.GetPvPQueue() end
function Game.GetRecipe() end
function Game.GetResourceNodeCompleteResults() end
function Game.GetResourceScanIds() end
function Game.GetResourceScanInfo() end
function Game.GetResourceTypeInfo() end
function Game.GetRootItemInfo() end
function Game.GetSinCardFields() end
function Game.GetSubzoneNameAt() end
function Game.GetTargetVitals() end
function Game.GetTargetBoneInfo() end
function Game.GetTargetBounds() end
function Game.GetTargetCharacterInfo() end
function Game.GetTargetHardpoints() end
function Game.GetTargetIdByName() end
function Game.GetTargetInfo() end
function Game.GetTargetRespawnTime() end
function Game.GetTargetStatus() end
function Game.GetTeamInfo() end
function Game.GetTeams() end
function Game.GetWarpaintInfo() end
function Game.GetWayPoint() end
function Game.GetWorldObjectInfo() end
function Game.GetworldObjectList() end
function Game.GetWorldObjectStatus() end
function Game.GetzoneInfo() end
function Game.HighlightEntity() end
function Game.IsInPvP() end
function Game.IsTargetAvailable() end
function Game.IsWorldMapVisible() end
function Game.QueueForPvP() end
function Game.RemoveRecipeFromCart() end
function Game.RequestDuel() end
function Game.RespondToServerQuery() end
function Game.SendDialogResponse() end
function Game.SendMissionUiMessage() end
function Game.SetMapCoordinates() end
function Game.SetMapCruiseControl() end
function Game.SetMapInputMode() end
function Game.SetRadarRange() end
function Game.SetTrailColor() end
function Game.SetTrailColor() end
function Game.SetTrailColor() end
function Game.SetWayPoint() end
function Game.ShowTrailTo() end
function Game.ShowWorldMap() end
function Game.SlashCommand() end
function Game.VoteForPvPMatch() end
function Game.WorldToChunkCoord() end
function Game.ZoomWorldMap() end
HTTP = {}
function HTTP.IsRequestPending() end
function HTTP.IssueRequest() end
Lobby = {}
function Lobby.AcceptInvite() end
function Lobby.Create() end
function Lobby.DeclineInvite() end
function Lobby.GetAvailableMaps() end
function Lobby.GetInvites() end
function Lobby.GetMatchParameters() end
function Lobby.GetRoster() end
function Lobby.Invite() end
function Lobby.Kick() end
function Lobby.Leave() end
function Lobby.ReadyCheck() end
function Lobby.SetPowerPrivilege() end
function Lobby.SetReady() end
function Lobby.SetTeam() end
function Lobby.SetZoneId() end
function Lobby.StartMatch() end
function Lobby.SwapTeam() end
Market = {}
function Market.SellItem() end
function Market.SellResourceStack() end
Paperdoll = {}
function Paperdoll.Create() end
function Paperdoll.Getdims() end
function Paperdoll.PlayEmote() end
function Paperdoll.SetEntityID() end
function Paperdoll.SetEquipment() end
function Paperdoll.SetPosition() end
function Paperdoll.SetRotation() end
function Paperdoll.SetScale() end
function Paperdoll.SetSpin() end
function Paperdoll.SetTeam() end
Player = {}
function Player.AbortMission() end
function Player.ActivateTech() end
function Player.BeginInteraction() end
function Player.CanDetectResources() end
function Player.EndInteraction() end
function Player.EquipLoadout() end
function Player.GetAbilityInfo() end
function Player.GetAbilityPoints() end
function Player.GetAbilityState() end
function Player.GetAchievementPointtotal() end
function Player.GetAchievementsIDs() end
function Player.GetAim() end
function Player.GetaimPosition() end
function Player.GetAttachmentId() end
function Player.GetCharacterId() end
function Player.GetCharacterState() end
function Player.GetClassProgression() end
function Player.GetCurrentOutpostId() end
function Player.GetDailyChallengeIds() end
function Player.GetDailyChallengeInfo() end
function Player.GetDailyChallengeProgress() end
function Player.GetDailyChallengeTime() end
function Player.GetEnergy() end
function Player.GetHardpointChoices() end
function Player.GetInteracteeInfo() end
function Player.GetItemCount() end
function Player.GetItemIdList() end
function Player.GetItemInfo() end
function Player.GetItems() end
function Player.GetLifeInfo() end
function Player.GetMissionIds() end
function Player.GetMissionInfo() end
function Player.GetPosition() end
function Player.GetResourceBoostModifier() end
function Player.GetSelfFeedbackposition() end
function Player.GetShoppingList() end
function Player.GetSinControlStatus() end
function Player.GetSpectatorMode() end
function Player.GetTargetId() end
function Player.GetTimePlayed() end
function Player.GetTrackedMissionId() end
function Player.GetWeaponCharge() end
function Player.GetWeaponIndex() end
function Player.GetWeaponInfo() end
function Player.GetWeaponMode() end
function Player.GetWeaponState() end
function Player.IsInVehicle() end
function Player.IsSpectating() end
function Player.PlaySinImprint() end
function Player.SelectHardpoint() end
function Player.SetForcedAfk() end
function Player.SlotTech() end
function Player.SpectatePlayer() end
function Player.SpendAbilityPointes() end
function Player.TrackMission() end
function Player.UpdateCraftInventory() end
function Player.UpdateDailyMissions() end
function Player.Updatemissions() end
Radio = {}
function Radio.PlayDailiescomplete() end
function Radio.PlayGreeting() end
function Radio.PlayJobOffer() end
function Radio.StartRadioDialog() end
function Radio.StartRadioWithSecureDialogId() end
Replay = {}
function Replay.SetAdvanceRate() end
function Replay.SetTime() end
function Replay.Skip() end
Sinvironment = {}
function Sinvironment.Activate() end
function Sinvironment.AlphaModelTo() end
function Sinvironment.BeginPlaceTatto() end
function Sinvironment.BeginPlaceTattoo() end
function Sinvironment.CreateModel() end
function Sinvironment.EnableMouseFocus() end
function Sinvironment.EndEditPattern() end
function Sinvironment.EndPlaceTattoo() end
function Sinvironment.FinishModelAlpha() end
function Sinvironment.FinishModelOrientation() end
function Sinvironment.FinishModelPosition() end
function Sinvironment.FinishModelScale() end
function Sinvironment.GetLightAnchor() end
function Sinvironment.GetModelAlpha() end
function Sinvironment.GetModelAnchor() end
function Sinvironment.GetModelBounds() end
function Sinvironment.GetModelOrientation() end
function Sinvironment.GetModelPosition() end
function Sinvironment.GetModelScale() end
function Sinvironment.GetModelShaderParamID() end
function Sinvironment.GetOrnamentVisuals() end
function Sinvironment.IsActive() end
function Sinvironment.IsValidModel() end
function Sinvironment.LoadCharacterComponent() end
function Sinvironment.LoadcharacterEyes() end
function Sinvironment.LoadcharacterOrnament() end
function Sinvironment.LoadItemType() end
function Sinvironment.LoadMonster() end
function Sinvironment.LoadZone() end
function Sinvironment.OrientationModelTo() end
function Sinvironment.ParamTo() end
function Sinvironment.ParamTo() end
function Sinvironment.PlayerModelAnimation() end
function Sinvironment.PositionModelTo() end
function Sinvironment.PreviewVoice() end
function Sinvironment.QueueModelAlpha() end
function Sinvironment.QueueModelOrientation() end
function Sinvironment.QueueModelPosition() end
function Sinvironment.QueueModelScale() end
function Sinvironment.RemoveLight() end
function Sinvironment.RemoveModel() end
function Sinvironment.ScaleModelTo() end
function Sinvironment.SetAnimatedCamera() end
function Sinvironment.SetCharacterSex() end
function Sinvironment.SetCharacterWarpaint() end
function Sinvironment.SetGradients() end
function Sinvironment.SetLightColor() end
function Sinvironment.SetManualCamera() end
function Sinvironment.SetModelAlpha() end
function Sinvironment.SetModelLOD() end
function Sinvironment.SetModelMaterialOverride() end
function Sinvironment.SetModelOrientation() end
function Sinvironment.SetModelPosition() end
function Sinvironment.SetModelScale() end
function Sinvironment.setModelShaderParam() end
function Sinvironment.SetPatternKeyState() end
function Sinvironment.SetPatterns() end
function Sinvironment.SetPatternTransform() end
function Sinvironment.SetTattooKeyState() end
function Sinvironment.SetTattooMatrix() end
function Sinvironment.SetTattoos() end
function Sinvironment.SetTattooTexture() end
function Sinvironment.ShaderParamModelTo() end
Squad = {}
function Squad.GetLeader() end
function Squad.AcceptInvite() end
function Squad.ClearWaypoint() end
function Squad.DeclineInvite() end
function Squad.GetMaxSquadSize() end
function Squad.GetRoster() end
function Squad.GetVitals() end
function Squad.GetWaypoint() end
function Squad.Invite() end
function Squad.IsLeaderInPvP() end
function Squad.IsLeaderOnSameInstance() end
function Squad.IsLeaderOnSameZone() end
function Squad.JoinLeader() end
function Squad.Kick() end
function Squad.Leave() end
function Squad.Promote() end
function Squad.RequestJoin() end
function Squad.SetWayPoint() end
System = {}
function System.ApplyKeyBindings() end
function System.ApplyRecommendedSettings() end
function System.ApplySettings() end
function System.AutoscaleUi() end
function System.BindDefaultKey() end
function System.BindKey() end
function System.BlurMainScene() end
function System.EnableSinTags() end
function System.GameSFXVolume() end
function System.GetAdvancedSettingsEnabled() end
function System.GetArg() end
function System.GetCdKey() end
function System.GetCharacterCreationPreviewZoom() end
function System.GetclientTime() end
function System.GetColorsList() end
function System.GetConfig() end
function System.GetCurrentFps() end
function System.GetCvar() end
function System.GetDesktopResolution() end
function System.GetElapsedTime() end
function System.GetElapsedUnixTime() end
function System.GetGpuDriverData() end
function System.GetHardwareSpecs() end
function System.GetHeadAccessoryList() end
function System.GetHeadList() end
function System.GetKeyBindings() end
function System.GetKeycodeString() end
function System.GetOperatorSetting() end
function System.GetRecommendedVideoQuality() end
function System.GetSettings() end
function System.GetSettingsRange() end
function System.GetVoiceList() end
function System.GoLookingGlass() end
function System.InvertGamepad() end
function System.InvertMouse() end
function System.IsFirstRun() end
function System.IsNewGpu() end
function System.IsUnderMinSpec() end
function System.LoginRequest()end
function System.ModifyPreviewCharacter() end
function System.ModifyPreviewCharacter() end
function System.Mute() end
function System.MuteMusic() end
function System.OpenUrl() end
function System.OverrideMusic() end
function System.PlaySound() end
function System.PlaySoundOnActor() end
function System.PopUrl() end
function System.RefreshSettings() end
function System.ScaleUi() end
function System.SetBattleChatterVolume() end
function System.SetCvar() end
function System.SetDialogVolume() end
function System.SetGamePlayback() end
function System.SetGameVolume() end
function System.SetGameVolume() end
function System.SetHitDingPitch() end
function System.SetHitDingVolume() end
function System.SetLastCharacter() end
function System.SetLocale() end
function System.SetMasterVolume() end
function System.SetModifierKey() end
function System.SetMusicVolume() end
function System.SetMute() end
function System.SetPreviewRotation() end
function System.SetRememberLogin() end
function System.SetResolution() end
function System.SetSettings() end
function System.SetupCharacter() end
function System.SpinCharacterCreationPreview() end
function System.SubmitFeedback() end
function System.SwapGamepadThumbsticks() end
function System.TakeScreenshot() end
function System.TestResolution() end
function System.TwitchAuth() end
function System.UpdateCharacterCreationPreview() end
function System.UseGtZone() end
function System.ZoomCharacterCreationPreview() end
function Vehicle.CalldownVehicle() end
function Vehicle.CommitConfiguration() end
function Vehicle.ConfigureVehicle() end
function Vehicle.GetComponentInfo() end
function Vehicle.GetVehicleConfig() end
function Vehicle.GetVehicleInfo() end
function Vehicle.GetVehicleInfo() end
function Vehicle.InstallComponent() end
function Vehicle.RemoveComponent() end